import json
from typing import Optional

from app.core.config import Settings
from app.models.schemas import GeneratedSQL, QueryRequest, SourceKind
from app.services.llm import OCIChatModelFactory
from app.services.metadata import CatalogMetadataService


class NL2SQLAgentService:
    def __init__(self, settings: Settings, metadata_service: CatalogMetadataService) -> None:
        self.settings = settings
        self.metadata_service = metadata_service
        self.llm = OCIChatModelFactory(settings).build()

    @property
    def mode(self) -> str:
        return "oci" if self.llm else "stub"

    def generate(self, request: QueryRequest) -> tuple[list[SourceKind], list[GeneratedSQL], Optional[str]]:
        sources = self._resolve_sources(request)

        if self.llm:
            candidate = self._generate_with_oci(request, sources)
            if candidate:
                return sources, candidate, self.settings.oci_model_id

        return sources, self._fallback_sql(request, sources), self.settings.oci_model_id

    def _resolve_sources(self, request: QueryRequest) -> list[SourceKind]:
        preferred = [source for source in request.source_preference if source != SourceKind.auto]
        if preferred:
            return preferred

        question = request.question.lower()
        if "iceberg" in question or "polaris" in question or "lakehouse" in question:
            return [SourceKind.polaris]
        if "mysql" in question:
            return [SourceKind.mysql]
        if "postgres" in question or "postgresql" in question:
            return [SourceKind.postgresql]
        if "oracle" in question:
            return [SourceKind.oracle]
        return [SourceKind.polaris, SourceKind.mysql, SourceKind.postgresql, SourceKind.oracle]

    def _generate_with_oci(
        self,
        request: QueryRequest,
        sources: list[SourceKind],
    ) -> Optional[list[GeneratedSQL]]:
        system_prompt = self._build_system_prompt()
        source_list = ", ".join(source.value for source in sources)
        human_prompt = f"""
Generate read-only SQL for the following question.

Question: {request.question}
Candidate sources: {source_list}
Maximum rows: {request.max_rows}

Respond as JSON with this shape:
{{
  "queries": [
    {{
      "source": "polaris",
      "statement": "SELECT ...",
      "rationale": "why this source was chosen"
    }}
  ]
}}
"""

        try:
            response = self.llm.invoke(
                [
                    ("system", system_prompt),
                    ("human", human_prompt),
                ]
            )
            payload = json.loads(getattr(response, "content", str(response)))
        except Exception:
            return None

        queries = payload.get("queries", [])
        generated: list[GeneratedSQL] = []
        for item in queries:
            try:
                generated.append(
                    GeneratedSQL(
                        source=SourceKind(item["source"]),
                        statement=item["statement"],
                        rationale=item.get("rationale", "Generated by OCI."),
                    )
                )
            except Exception:
                continue

        return generated or None

    def _build_system_prompt(self) -> str:
        return (
            "You are an enterprise NL2SQL assistant.\n"
            "Generate only read-only SQL.\n"
            "Prefer the smallest set of sources that can answer the question.\n"
            "Use Spark-compatible SQL when possible.\n"
            "Do not invent tables or columns.\n"
            "Use the metadata context below.\n\n"
            f"{self.metadata_service.prompt_context()}"
        )

    def _fallback_sql(self, request: QueryRequest, sources: list[SourceKind]) -> list[GeneratedSQL]:
        question = request.question.lower()
        statements: list[GeneratedSQL] = []

        for source in sources:
            if source == SourceKind.polaris:
                statement = (
                    "SELECT customer_id, order_total, order_ts\n"
                    "FROM polaris.sales.orders\n"
                    "ORDER BY order_ts DESC"
                )
            elif source == SourceKind.mysql:
                statement = (
                    "SELECT customer_id, customer_name, region\n"
                    "FROM mysql.crm_customers\n"
                    "ORDER BY customer_name"
                )
            elif source == SourceKind.postgresql:
                statement = (
                    "SELECT product_id, product_name, category\n"
                    "FROM postgresql.inventory_products\n"
                    "ORDER BY product_name"
                )
            else:
                statement = (
                    "SELECT invoice_id, account_id, invoice_total\n"
                    "FROM oracle.ar_invoices\n"
                    "ORDER BY invoice_id DESC"
                )

            if "count" in question:
                statement = f"SELECT COUNT(*) AS row_count\nFROM ({statement}) base_query"
            elif "top" in question or "highest" in question:
                statement = statement.replace("ORDER BY", "ORDER BY")

            statements.append(
                GeneratedSQL(
                    source=source,
                    statement=statement,
                    rationale=f"Stub SQL for {source.value}; replace with OCI-generated SQL after credentials are configured.",
                )
            )

        return statements
